(function(g){var e={$el:{body:"body",modal_win:".modal-win",shadow:".modal-win-shadow"},settings:{start_zI:1E3,step_zI:10,once:!1,close_class:".close-button",close_shadow:!0,ajax_url:!1,ajax_method:"GET",ajax_type:!1,ajax_data:!1,ajax_append:!1,ajax_cache:!1,isLoad:!1},CACHE:[],before:function(){},after:function(){},always:function(){},close:function(a){},window:{tag:"div","class":"modal-win",style:{position:"fixed",top:"0",left:"0",width:"100%",height:"100%","text-align":"center",overflow:"auto"},
attr:{},"sep-top":["div","modal-win-space-top","position:relative;width:100%;height:50px;"],"sep-down":["div","modal-win-space-bottom","position:relative;width:100%;height:40px;"]},container:{tag:"div",id:!1,"class":"modal-win-container",html:"",style:{position:"relative","text-align":"left",margin:"0 auto",width:"700px",background:"#fff","z-index":"5","min-height":"16px"},attr:{}},shadow:{tag:"div","class":"modal-win-shadow",style:{position:"fixed",top:"0",left:"0",width:"100%",height:"100%",background:"#000"},
attr:{},animate:{"disable-any":!0,"on-style":{opacity:0.4},"off-style":{opacity:0},"speed-show":500,"speed-hide":500},animateOn:function(a){if("object"!=typeof a||"object"!=typeof a["on-style"])return this.window.show();if(0==a["speed-show"]||"boolean"==typeof a["speed-show"])this.shadow.css(a["on-style"]),this.window.show();else{var b=this.window;this.shadow.animate(a["on-style"],a["speed-show"],function(){b.show()})}},animateOff:function(a){if("object"!=typeof a||"object"!=typeof a["off-style"]||
0==a["speed-hide"]||"boolean"==typeof a["speed-hide"])return this.window.trigger("Remove");var b=this.window;this.shadow.animate(a["off-style"],a["speed-hide"],function(){b.trigger("Remove")})}},ajax:{init:function(a){var b=this,d=!1;if("string"!=typeof a.settings.ajax_url||!1===a.settings.ajax_url)d=!0;!0==a.settings.once&&!0==a.settings.isLoad&&(d=!0);if(d)return a.always.call(b,!1);d={url:a.settings.ajax_url,type:a.settings.ajax_method};"string"==typeof a.settings.ajax_type&&(d.dataType=a.settings.ajax_type);
"boolean"==typeof a.settings.ajax_cache&&(d.cache=a.settings.ajax_cache);if("object"==typeof a.settings.ajax_data||"string"==typeof a.settings.ajax_data)d.data=a.settings.ajax_data;d.success=a.ajax.onload;d.e=b;d.after=a.after;d.ajax_append=a.settings.ajax_append;g.ajax(d).done(function(d){a.settings.isLoad=!0;a.always.call(b,d)})},onload:function(a){this.e.data=a;var b=this.after.call(this.e);"object"!=typeof a&&!1!==b&&(!0==this.ajax_append?this.e.container.append(a):this.e.container.html(a))}},
_$:{elem_list:function(){return g(this.$el.body+", "+this.$el.modal_win)},shadow_list:function(){},create:function(a){if("object"!=typeof a||"string"!=typeof a.tag)return g("<div>");var b=g("<"+a.tag+">");"object"==typeof a.attr&&b.attr(a.attr);"string"==typeof a["class"]&&b.addClass(a["class"]);"object"==typeof a.style&&b.css(a.style);"string"==typeof a.id&&b.attr("id",a.id);"string"==typeof a.html&&b.html(a.html);return b}},get_zIndex:function(){return this.settings.start_zI+=this.settings.step_zI},
set_all_overflow:function(){this._$.elem_list.call(this).css("overflow","hidden")},set_floor_overflow:function(){this.set_all_overflow();var a=this.CACHE.length-1;"object"==typeof this.CACHE[a]&&this.CACHE[a][0].window.css("overflow","auto")},clone:function(a){var b,d={};a="object"!=typeof a?{}:a;for(b in a)"CACHE"!=b&&a.hasOwnProperty(b)&&(d[b]="object"==typeof a[b]?e.clone(a[b]):a[b]);return d},remove:function(){for(var a=[],b=new Function,d=!1,f=e.CACHE.length-1;0<=f;f--)"object"==typeof e.CACHE[f]&&
a.push(f);for(f=0;f<=a.length;f++)if("none"!=e.CACHE[a[f]][0].window.css("display")){var c=e.CACHE[a[f]][0],h=c.window,m=c.shadow,k=e.CACHE[a[f]][1];k.settings.once?b=function(a){!1!==k.close.call(c,!0)&&(g(this).hide(),a.data.shadow.hide(),g(this).trigger("unlock"))}:(b=function(a){!1!==k.close.call(c,!1)&&(g(this).detach(),a.data.shadow.remove(),g(this).trigger("unlock").remove())},delete e.CACHE[a[f]]);break}"undefined"!=typeof a[f+1]&&(d=this.CACHE[a[f+1]][0].window||!1);a="object"!=typeof d?
function(){g(k.$el.body).css("overflow","auto")}:function(){d.css("overflow","auto")};h.on("Remove",{shadow:m},b);h.on("unlock",a);k.shadow.animateOff.call(c,k.shadow.animate)},init:function(){this.set_all_overflow.call(this);var a=e.get_zIndex(),b=this._$.create(this.window).hide().css("zIndex",a),d=this._$.create({tag:this.window["sep-top"][0],"class":this.window["sep-top"][1],attr:{style:this.window["sep-top"][2]}}),f=this._$.create({tag:this.window["sep-down"][0],"class":this.window["sep-down"][1],
attr:{style:this.window["sep-down"][2]}}),c=this._$.create(this.container),a=this._$.create(this.shadow).css("zIndex",a-1).css(this.shadow.animate["off-style"]),h={window:b,"sep-top":d,container:c,"sep-down":f,shadow:a};b.append(d).append(c).append(f);g(this.$el.body).prepend(a).prepend(b);e.CACHE[e.CACHE.length]=[h,this];a.on("close",function(a){b.trigger("close")});b.on("close",function(a){e.remove()});if(!0==this.settings.close_shadow)b.on("click",function(a){g(a.target).is(c)||g(a.target).parents().is(c)||
b.trigger("close")});g(this.settings.close_class,b).on("click",function(){b.trigger("close")});this.before.call(h);this.ajax.init.call(h,this);this.shadow.animateOn.call(h,this.shadow.animate)},re_init:function(a){var b=e.get_zIndex(),d=a.shadow;a.window.css("zIndex",b);d.css("zIndex",b-1);e.set_floor_overflow();this.ajax.init.call(a,this);"none"==a.window.css("display")&&(a.shadow.show(),this.shadow.animateOn.call(a,this.shadow.animate))}},l=function(a,b){if("object"!=typeof a)return b;b.container.id=
"string"==typeof a.id?a.id:!1;b.settings.once="boolean"==typeof a.once?a.once:!1;b.container.html="string"==typeof a.html?a.html:b.container.html;"string"==typeof a["top-space"]&&(b.window["sep-top"][2]=b.window["sep-top"][2].replace(/height:\d*.*;/,"height:"+a["top-space"]+";"));"string"==typeof a["bottom-space"]&&(b.window["sep-down"][2]=b.window["sep-down"][2].replace(/height:\d*.*;/,"height:"+a["bottom-space"]+";"));"string"==typeof a.shadow&&(b.shadow.style.background=a.shadow);b.settings.ajax_append=
"boolean"==typeof a.append?a.append:b.settings.ajax_append;b.settings.close_class="string"==typeof a.close?a.close:b.settings.close_class;b.settings.ajax_url="string"==typeof a.url?a.url:b.settings.ajax_url;b.settings.ajax_url="boolean"==typeof a.url?a.url:b.settings.ajax_url;b.settings.ajax_url="string"==typeof a.load?a.load:b.settings.ajax_url;b.settings.ajax_url="boolean"==typeof a.load?a.load:b.settings.ajax_url;b.settings.ajax_method="string"==typeof a.ajax_method?a.ajax_method:"GET";b.settings.ajax_data=
"string"==typeof a.ajax_data?a.ajax_data:b.settings.ajax_data;b.settings.ajax_data="object"==typeof a.ajax_data?a.ajax_data:b.settings.ajax_data;b.settings.ajax_data="boolean"==typeof a.ajax_data?a.ajax_data:b.settings.ajax_data;b.container.html="string"==typeof a.container?a.container:b.container.html;if("object"==typeof a.container){var d,f,c,e;for(d in a.container)if(c=a.container[d],f=typeof c,"object"==f)for(e in c)b.container[d][e]=c[e];else b.container[d]=c}if("object"==typeof a.window)for(d in a.window)if(c=
a.window[d],f=typeof c,"object"==f)for(e in c)b.window[d][e]=c[e];else b.window[d]=c;if("object"==typeof a.shadow)for(d in a.shadow)if(c=a.shadow[d],f=typeof c,"object"==f)for(e in c)b.shadow[d][e]=c[e];else switch(d){case "opacity":b.shadow.animate["on-style"].opacity=c;break;case "animate-opacity":b.shadow.animate["off-style"].opacity=c;break;case "animate-show":b.shadow.animate["speed-show"]=c;break;case "animate-hide":b.shadow.animate["speed-hide"]=c;break;case "background":b.shadow.style.background=
c;break;case "close":b.settings.close_shadow="boolean"==typeof c?c:b.settings.close_shadow;break;case "animateOn":b.shadow.animateOn="function"==typeof c?c:b.settings.close_shadow;break;case "animateOff":b.shadow.animateOff="function"==typeof c?c:b.settings.close_shadow;break;default:b.shadow[d]=a.shadow[d]}"object"==typeof a.close&&(b.settings.close_class="string"==typeof a.close["class"]?a.close["class"]:b.settings.close_class,b.settings.close_shadow="boolean"==typeof a.close.shadow?a.close.shadow:
b.settings.close_shadow);"object"==typeof a.load&&(b.settings.ajax_url="string"==typeof a.load.url?a.load.url:b.settings.ajax_url,b.settings.ajax_url="boolean"==typeof a.load.url?a.load.url:b.settings.ajax_url,b.settings.ajax_method="string"==typeof a.load.method?a.load.method:"GET",b.settings.ajax_data="string"==typeof a.load.data?a.load.data:b.settings.ajax_data,b.settings.ajax_data="object"==typeof a.load.data?a.load.data:b.settings.ajax_data,b.settings.ajax_data="boolean"==typeof a.load.data?
a.load.data:b.settings.ajax_data,b.settings.ajax_append="boolean"==typeof a.load.append?a.load.append:b.settings.ajax_append);"object"==typeof a.call&&(b.before="function"==typeof a.call.before?a.call.before:b.before,b.after="function"==typeof a.call.after?a.call.after:b.after,b.always="function"==typeof a.call.always?a.call.always:b.always,b.close="function"==typeof a.call.close?a.call.close:b.close);return b};g.ModalWin=function(a){var b={},d=!1;if("object"==typeof a&&"string"==typeof a.id){var f,
c=0,g=a.id.replace(/^#{1}/,"");for(c;c<e.CACHE.length;c++)if("object"==typeof e.CACHE[c]&&e.CACHE[c][0].container.attr("id")==g){d=!0;f=e.CACHE[c][0];b=e.CACHE[c][1];e.CACHE[e.CACHE.length]=[f,b];delete e.CACHE[c];break}}d?e.re_init.call(b,f):(b=e.clone(e),b=l(a,b),e.init.call(b))};g.ModalWin_CORE=e;g.ModalWin_install=l})(jQuery);
